<div class="modal fade" id="impulso-new-conversation-modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header"><div class="impulso-modal-title"><div class="impulso-modal-title-icon"><i data-feather="message-circle"></i></div><div><h4>Nova conversa</h4><p>Inicie um atendimento por uma instância conectada</p></div></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button></div>
            <div class="modal-body">
                <div class="impulso-field-grid">
                    <div class="impulso-field full"><label>Contato ou telefone</label><div class="impulso-search-field"><i data-feather="search"></i><input class="form-control" id="impulso-new-conversation-contact" placeholder="Nome ou 5511999999999" autocomplete="off"></div><div class="impulso-suggestion-list impulso-hidden" id="impulso-new-conversation-suggestions"></div></div>
                    <div class="impulso-field"><label>Instância</label><select class="form-control" id="impulso-new-conversation-instance"><option value="">Selecione</option><?php foreach (($instances ?? []) as $instance) { ?><option value="<?php echo (int) ($instance['id'] ?? 0); ?>" <?php echo ($instance['status'] ?? '') !== 'connected' ? 'disabled' : ''; ?>><?php echo esc($instance['name'] ?? ''); ?><?php echo ($instance['status'] ?? '') !== 'connected' ? ' — desconectada' : ''; ?></option><?php } ?></select></div>
                    <div class="impulso-field"><label>Nome do contato</label><input class="form-control" id="impulso-new-conversation-name" placeholder="Opcional para novos números"></div>
                    <div class="impulso-field full"><label>Mensagem inicial</label><textarea class="form-control" id="impulso-new-conversation-message" rows="5" placeholder="Escreva a primeira mensagem"></textarea><small><span id="impulso-new-conversation-char-count">0</span> caracteres</small></div>
                </div>
            </div>
            <div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancelar</button><button type="button" class="btn btn-primary" data-impulso-modal-submit="conversation"><i data-feather="send"></i> Iniciar conversa</button></div>
        </div>
    </div>
</div>

<div class="modal fade" id="impulso-new-contact-modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header"><div class="impulso-modal-title"><div class="impulso-modal-title-icon"><i data-feather="user-plus"></i></div><div><h4 id="impulso-contact-modal-title">Novo contato</h4><p>Cadastre ou atualize os dados do cliente</p></div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
            <div class="modal-body"><input type="hidden" id="impulso-contact-id"><div class="impulso-field-grid">
                <div class="impulso-field full"><label>Nome</label><input class="form-control" id="impulso-contact-form-name" maxlength="150" placeholder="Nome completo"></div>
                <div class="impulso-field"><label>Telefone</label><input class="form-control" id="impulso-contact-form-phone" maxlength="32" placeholder="5511999999999"></div>
                <div class="impulso-field"><label>E-mail</label><input class="form-control" id="impulso-contact-form-email" type="email" placeholder="email@empresa.com"></div>
                <div class="impulso-field"><label>Empresa</label><input class="form-control" id="impulso-contact-form-company" placeholder="Empresa ou projeto"></div>
                <div class="impulso-field"><label>Cidade</label><input class="form-control" id="impulso-contact-form-city" placeholder="Cidade"></div>
                <div class="impulso-field"><label>Origem</label><select class="form-control" id="impulso-contact-form-source"><option value="whatsapp">WhatsApp</option><option value="campaign">Campanha</option><option value="manual">Cadastro manual</option><option value="meta">Meta Ads</option><option value="other">Outra</option></select></div>
                <div class="impulso-field"><label>Instância preferencial</label><select class="form-control" id="impulso-contact-form-instance"><option value="">Nenhuma</option><?php foreach (($instances ?? []) as $instance) { ?><option value="<?php echo (int) ($instance['id'] ?? 0); ?>"><?php echo esc($instance['name'] ?? ''); ?></option><?php } ?></select></div>
                <div class="impulso-field full"><label>Etiquetas</label><input class="form-control" id="impulso-contact-form-tags" placeholder="lead, matrícula, urgente"><small>Separe as etiquetas por vírgula.</small></div>
                <div class="impulso-field full"><label>Observações</label><textarea class="form-control" id="impulso-contact-form-notes" rows="4" placeholder="Informações úteis para o atendimento"></textarea></div>
                <div class="impulso-field full"><label class="form-check"><input class="form-check-input" id="impulso-contact-form-opt-out" type="checkbox"> <span class="form-check-label">Bloquear este contato para campanhas</span></label></div>
            </div></div>
            <div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancelar</button><button type="button" class="btn btn-primary" data-impulso-modal-submit="contact"><i data-feather="save"></i> Salvar contato</button></div>
        </div>
    </div>
</div>

<div class="modal fade" id="impulso-instance-modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header"><div class="impulso-modal-title"><div class="impulso-modal-title-icon"><i data-feather="smartphone"></i></div><div><h4 id="impulso-instance-modal-title">Nova instância Evolution</h4><p>Cadastre uma sessão existente na Evolution API</p></div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
            <div class="modal-body"><input id="impulso-instance-id" type="hidden" value=""><div class="impulso-field-grid">
                <div class="impulso-field"><label>Nome de exibição</label><input class="form-control" id="impulso-instance-name" maxlength="150" required placeholder="Ex.: SIAMESA SBC"></div>
                <div class="impulso-field"><label>Nome na Evolution</label><input class="form-control" id="impulso-instance-technical-name" maxlength="191" required placeholder="siamesa_sbc"></div>
                <div class="impulso-field"><label>Identificação interna</label><input class="form-control" id="impulso-instance-identifier" maxlength="191" required placeholder="comercial_sbc"></div>
                <div class="impulso-field"><label>Número conectado</label><input class="form-control" id="impulso-instance-phone" maxlength="32" placeholder="5511999999999"></div>
                <div class="impulso-field full"><label>URL base específica</label><input class="form-control" id="impulso-instance-base-url" type="url" placeholder="Vazio para usar a URL global" <?php echo empty($can_manage_settings) ? 'disabled' : ''; ?>><?php if (empty($can_manage_settings)) { ?><small>Somente usuários com permissão de configurações podem alterar o destino da API.</small><?php } ?></div>
                <div class="impulso-field full"><label>API key específica</label><div class="input-group"><input class="form-control" id="impulso-instance-api-key" type="password" value="" autocomplete="new-password" placeholder="Vazio para manter/usar a chave global"><button class="btn btn-default" type="button" data-impulso-action="toggle-password"><i data-feather="eye"></i></button></div></div>
                <div class="impulso-field full"><label class="form-check"><input class="form-check-input" id="impulso-instance-clear-api-key" type="checkbox"> <span class="form-check-label">Remover a chave específica atual e usar a configuração global</span></label></div>
                <div class="impulso-field full"><label class="form-check"><input class="form-check-input" id="impulso-instance-active" type="checkbox" checked> <span class="form-check-label">Instância ativa</span></label></div>
            </div></div>
            <div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancelar</button><button type="button" class="btn btn-primary" data-impulso-modal-submit="instance"><i data-feather="save"></i> Salvar instância</button></div>
        </div>
    </div>
</div>

<div class="modal fade" id="impulso-campaign-modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="modal-header"><div class="impulso-modal-title"><div class="impulso-modal-title-icon"><i data-feather="send"></i></div><div><h4 id="impulso-campaign-modal-title">Nova campanha</h4><p>Defina público, conteúdo, segurança e agendamento</p></div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
            <div class="modal-body"><input type="hidden" id="impulso-campaign-id"><div class="impulso-builder-steps" id="impulso-campaign-steps"><button class="impulso-builder-step active" type="button" data-campaign-step="1"><span>1</span> Campanha</button><button class="impulso-builder-step" type="button" data-campaign-step="2"><span>2</span> Público</button><button class="impulso-builder-step" type="button" data-campaign-step="3"><span>3</span> Mensagem</button><button class="impulso-builder-step" type="button" data-campaign-step="4"><span>4</span> Agendamento</button></div>
                <div class="impulso-campaign-form-step" data-campaign-panel="1"><div class="impulso-field-grid"><div class="impulso-field full"><label>Nome da campanha</label><input class="form-control" id="impulso-campaign-name" maxlength="150" placeholder="Ex.: Reativação de leads de julho"></div><div class="impulso-field"><label>Instância</label><select class="form-control" id="impulso-campaign-instance"><option value="">Selecione</option><?php foreach (($instances ?? []) as $instance) { ?><option value="<?php echo (int) ($instance['id'] ?? 0); ?>"><?php echo esc($instance['name'] ?? ''); ?></option><?php } ?></select></div><div class="impulso-field"><label>Tipo</label><select class="form-control" id="impulso-campaign-type"><option value="one_time">Disparo único</option><option value="recurring">Recorrente</option><option value="triggered">Por gatilho</option></select></div><div class="impulso-field full"><label>Descrição interna</label><textarea class="form-control" id="impulso-campaign-description" rows="3" placeholder="Objetivo e observações"></textarea></div></div></div>
                <div class="impulso-campaign-form-step impulso-hidden" data-campaign-panel="2"><div class="impulso-grid impulso-grid-2"><div class="impulso-field-grid"><div class="impulso-field full"><label>Fonte do público</label><select class="form-control" id="impulso-campaign-audience-source"><option value="contacts">Contatos do Impulso Hub</option><option value="manual">Lista manual</option><option value="csv">Arquivo CSV</option><option value="n8n">Público definido pelo n8n</option></select></div><div class="impulso-field full"><label>Etiquetas incluídas</label><input class="form-control" id="impulso-campaign-include-tags" placeholder="lead, interessado"></div><div class="impulso-field full"><label>Etiquetas excluídas</label><input class="form-control" id="impulso-campaign-exclude-tags" placeholder="matriculado, opt-out"></div><div class="impulso-field full"><label>Números manuais</label><textarea class="form-control" id="impulso-campaign-manual-numbers" rows="7" placeholder="Um número por linha"></textarea></div></div><div class="impulso-audience-preview"><div class="impulso-audience-count"><span>Público estimado</span><strong id="impulso-campaign-audience-count">0</strong></div><div class="impulso-setting-row"><div class="impulso-setting-copy"><strong>Opt-outs removidos</strong><span>Aplicado automaticamente</span></div><span class="impulso-badge success"><i data-feather="shield"></i> Ativo</span></div><div class="impulso-setting-row"><div class="impulso-setting-copy"><strong>Números duplicados</strong><span>Removidos antes do envio</span></div><span class="impulso-badge success">Ativo</span></div><button class="btn btn-default btn-block" type="button" data-impulso-action="preview-campaign-audience"><i data-feather="users"></i> Calcular público</button></div></div></div>
                <div class="impulso-campaign-form-step impulso-hidden" data-campaign-panel="3"><div class="impulso-grid impulso-grid-2"><div><div class="impulso-field full"><label>Mensagem</label><textarea class="form-control" id="impulso-campaign-message" rows="10" placeholder="Olá, {nome}! Ainda tem interesse..."></textarea><div class="impulso-inline impulso-gap-8 impulso-mt-8"><button class="btn btn-default btn-sm" type="button" data-impulso-action="campaign-emoji"><i data-feather="smile"></i> Emoji</button><button class="btn btn-default btn-sm" type="button" data-impulso-action="campaign-variable" data-variable="{nome}">{nome}</button><button class="btn btn-default btn-sm" type="button" data-impulso-action="campaign-variable" data-variable="{empresa}">{empresa}</button><button class="btn btn-default btn-sm" type="button" data-impulso-action="campaign-attachment"><i data-feather="paperclip"></i> Mídia</button></div><input type="file" id="impulso-campaign-file" hidden accept="image/*,video/*,audio/*,.pdf"></div></div><div><div class="impulso-phone-preview"><div class="impulso-phone-top"><strong id="impulso-campaign-preview-title">Campanha</strong><span>prévia</span></div><div class="impulso-phone-screen"><div class="impulso-wa-bubble" id="impulso-campaign-preview">Sua mensagem aparecerá aqui.<span class="impulso-wa-time">agora</span></div></div></div></div></div></div>
                <div class="impulso-campaign-form-step impulso-hidden" data-campaign-panel="4"><div class="impulso-field-grid"><div class="impulso-field"><label>Início</label><input class="form-control" id="impulso-campaign-start-date" type="date"></div><div class="impulso-field"><label>Horário</label><input class="form-control" id="impulso-campaign-start-time" type="time"></div><div class="impulso-field"><label>Fim da janela</label><input class="form-control" id="impulso-campaign-end-time" type="time" value="20:00"></div><div class="impulso-field"><label>Intervalo entre mensagens</label><input class="form-control" id="impulso-campaign-interval" type="number" min="1" max="3600" value="10"><small>Segundos</small></div><div class="impulso-field full"><label>Dias da semana</label><div class="impulso-weekdays" id="impulso-campaign-weekdays"><?php foreach (['seg'=>'Seg','ter'=>'Ter','qua'=>'Qua','qui'=>'Qui','sex'=>'Sex','sab'=>'Sáb','dom'=>'Dom'] as $key=>$label) { ?><label><input type="checkbox" value="<?php echo $key; ?>" <?php echo in_array($key,['seg','ter','qua','qui','sex'],true) ? 'checked' : ''; ?>><span><?php echo $label; ?></span></label><?php } ?></div></div><div class="impulso-field full"><label class="form-check"><input class="form-check-input" id="impulso-campaign-start-immediately" type="checkbox"> <span class="form-check-label">Iniciar imediatamente após salvar</span></label></div></div></div>
            </div>
            <div class="modal-footer"><button type="button" class="btn btn-default" data-impulso-action="campaign-previous" id="impulso-campaign-previous" disabled>Voltar</button><div class="impulso-flex-spacer"></div><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancelar</button><button type="button" class="btn btn-primary" data-impulso-action="campaign-next" id="impulso-campaign-next">Continuar</button><button type="button" class="btn btn-success impulso-hidden" data-impulso-modal-submit="campaign" id="impulso-campaign-save"><i data-feather="calendar"></i> Salvar campanha</button></div>
        </div>
    </div>
</div>

<div class="modal fade" id="impulso-ai-modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><div class="modal-header"><div class="impulso-modal-title"><div class="impulso-modal-title-icon"><i data-feather="cpu"></i></div><div><h4 id="impulso-ai-modal-title">Novo agente</h4><p>Vincule uma instância a um fluxo do n8n</p></div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="impulso-agent-id"><div class="impulso-field-grid"><div class="impulso-field"><label>Nome</label><input class="form-control" id="impulso-agent-name" placeholder="Ex.: IARA Matrículas"></div><div class="impulso-field"><label>Instância</label><select class="form-control" id="impulso-agent-instance"><option value="">Todas as instâncias</option><?php foreach (($instances ?? []) as $instance) { ?><option value="<?php echo (int) ($instance['id'] ?? 0); ?>"><?php echo esc($instance['name'] ?? ''); ?></option><?php } ?></select></div><div class="impulso-field full"><label>Webhook/endpoint de controle do n8n</label><input class="form-control" id="impulso-agent-webhook" type="url" placeholder="https://n8n.exemplo.com/webhook/..."></div><div class="impulso-field"><label>Workflow ID</label><input class="form-control" id="impulso-agent-workflow-id" placeholder="ID do workflow"></div><div class="impulso-field"><label>Modo padrão</label><select class="form-control" id="impulso-agent-default-mode"><option value="running">IA ativa</option><option value="paused">IA pausada</option><option value="human">Atendimento humano</option></select></div><div class="impulso-field full"><label>Descrição operacional</label><textarea class="form-control" id="impulso-agent-description" rows="4" placeholder="Função do agente e momento de handoff"></textarea></div><div class="impulso-field full"><label class="form-check"><input class="form-check-input" id="impulso-agent-active" type="checkbox" checked> <span class="form-check-label">Agente ativo</span></label></div></div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancelar</button><button type="button" class="btn btn-primary" data-impulso-modal-submit="agent"><i data-feather="save"></i> Salvar agente</button></div></div></div>
</div>

<div class="modal fade" id="impulso-automation-modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><div class="modal-header"><div class="impulso-modal-title"><div class="impulso-modal-title-icon"><i data-feather="git-branch"></i></div><div><h4>Nova automação</h4><p>Configure um gatilho que chama o n8n</p></div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="impulso-automation-id"><div class="impulso-field-grid"><div class="impulso-field"><label>Nome</label><input class="form-control" id="impulso-automation-name"></div><div class="impulso-field"><label>Gatilho</label><select class="form-control" id="impulso-automation-trigger"><option value="message_received">Mensagem recebida</option><option value="conversation_created">Conversa criada</option><option value="tag_added">Etiqueta adicionada</option><option value="conversation_resolved">Conversa resolvida</option><option value="schedule">Agendamento</option></select></div><div class="impulso-field full"><label>Webhook do n8n</label><input class="form-control" id="impulso-automation-webhook" type="url"></div><div class="impulso-field full"><label>Condições em JSON</label><textarea class="form-control impulso-code-input" id="impulso-automation-conditions" rows="6" placeholder='{"instance_id": 1}'></textarea></div><div class="impulso-field full"><label class="form-check"><input class="form-check-input" id="impulso-automation-active" type="checkbox" checked> <span class="form-check-label">Automação ativa</span></label></div></div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancelar</button><button type="button" class="btn btn-primary" data-impulso-modal-submit="automation"><i data-feather="save"></i> Salvar automação</button></div></div></div>
</div>

<div class="modal fade" id="impulso-media-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-xl"><div class="modal-content impulso-media-modal-content"><div class="modal-header"><div><h4 id="impulso-media-title">Mídia</h4><p id="impulso-media-description"></p></div><div class="impulso-inline impulso-gap-8"><a class="btn btn-default btn-sm" id="impulso-media-download" href="#" download target="_blank"><i data-feather="download"></i> Baixar</a><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div></div><div class="modal-body" id="impulso-media-stage"></div></div></div></div>

<div class="modal fade" id="impulso-global-search-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><div class="modal-body impulso-command-palette"><div class="impulso-command-search"><i data-feather="search"></i><input id="impulso-global-search-input" type="search" placeholder="Busque conversas, contatos, campanhas ou configurações" autocomplete="off"><kbd>ESC</kbd></div><div class="impulso-command-results" id="impulso-global-search-results"><div class="impulso-command-section"><span>Ações rápidas</span><button type="button" data-command-action="new-conversation"><i data-feather="message-circle"></i><div><strong>Nova conversa</strong><small>Enviar mensagem por uma instância conectada</small></div></button><button type="button" data-command-action="new-contact"><i data-feather="user-plus"></i><div><strong>Novo contato</strong><small>Cadastrar contato manualmente</small></div></button><button type="button" data-command-action="new-campaign"><i data-feather="send"></i><div><strong>Nova campanha</strong><small>Criar um disparo pelo n8n</small></div></button></div></div></div></div></div></div>

<div class="impulso-notification-drawer" id="impulso-notification-drawer" aria-hidden="true"><div class="impulso-drawer-header"><div><span class="impulso-eyebrow">Central</span><h3>Notificações</h3></div><button class="impulso-icon-button btn btn-default" type="button" data-impulso-action="close-notifications"><i data-feather="x"></i></button></div><div class="impulso-drawer-tabs"><button class="active" type="button" data-notification-filter="all">Todas</button><button type="button" data-notification-filter="unread">Não lidas</button><button type="button" data-notification-filter="system">Sistema</button></div><div class="impulso-drawer-body" id="impulso-notification-list"><div class="impulso-empty compact"><p>Nenhuma notificação carregada.</p></div></div><div class="impulso-drawer-footer"><button class="btn btn-default btn-block" type="button" data-impulso-action="mark-all-notifications-read">Marcar todas como lidas</button></div></div><div class="impulso-drawer-backdrop" id="impulso-drawer-backdrop"></div>

<div class="impulso-context-menu impulso-hidden" id="impulso-context-menu"></div>
<div class="impulso-toast-stack" id="impulso-toast-stack"></div>
