<div class="impulso-page" id="impulso-settings-page">
    <div class="impulso-section-heading">
        <div>
            <h2>Configurações</h2>
            <p>Centralize Evolution API, n8n, campanhas, IA, notificações e retenção.</p>
        </div>
        <div class="impulso-section-actions">
            <?php if (!empty($can_manage_instances)) { ?><button class="btn btn-default" type="button" data-impulso-action="test-all-connections"><i data-feather="activity"></i> Testar conexões</button><?php } ?>
            <?php if (!empty($can_manage_settings)) { ?><button class="btn btn-primary" type="button" data-impulso-action="save-settings"><i data-feather="save"></i> Salvar alterações</button><?php } ?>
        </div>
    </div>

    <div class="impulso-settings-layout">
        <nav class="impulso-settings-nav">
            <button class="active" type="button" data-settings-tab="general"><i data-feather="sliders"></i> Geral</button>
            <button type="button" data-settings-tab="evolution"><i data-feather="smartphone"></i> Evolution API</button>
            <button type="button" data-settings-tab="n8n"><i data-feather="git-branch"></i> n8n</button>
            <button type="button" data-settings-tab="campaigns"><i data-feather="send"></i> Campanhas</button>
            <button type="button" data-settings-tab="ai"><i data-feather="cpu"></i> IA e automações</button>
            <button type="button" data-settings-tab="webhooks"><i data-feather="radio"></i> Webhooks</button>
            <button type="button" data-settings-tab="security"><i data-feather="shield"></i> Segurança</button>
        </nav>

        <div>
            <section class="impulso-settings-panel active" data-settings-panel="general">
                <div class="impulso-card impulso-mb-14">
                    <div class="impulso-card-header"><div><h3>Experiência de atendimento</h3><p>Comportamento padrão do front</p></div></div>
                    <div class="impulso-card-body">
                        <div class="impulso-field-grid">
                            <div class="impulso-field"><label>Nome do módulo</label><input class="form-control" id="impulso-setting-module-name" value="<?php echo esc($settings_public['module_name'] ?? 'Impulso Hub'); ?>"></div>
                            <div class="impulso-field"><label>Fuso horário</label><select class="form-control" id="impulso-setting-timezone"><option value="America/Sao_Paulo">America/Sao_Paulo (UTC-03:00)</option></select></div>
                            <div class="impulso-field"><label>Intervalo do polling</label><input class="form-control" id="impulso-setting-polling" type="number" min="3000" max="60000" step="1000" value="<?php echo (int) ($settings_public['polling_interval_ms'] ?? 5000); ?>"><small>Milissegundos</small></div>
                            <div class="impulso-field"><label>Quantidade por página</label><input class="form-control" id="impulso-setting-page-size" type="number" min="10" max="100" value="<?php echo (int) ($settings_public['conversation_page_size'] ?? 30); ?>"></div>
                        </div>
                        <div class="impulso-setting-row impulso-mt-14"><div class="impulso-setting-copy"><strong>Som para novas mensagens</strong><span>Reproduzir um aviso quando chegar mensagem em conversa não aberta.</span></div><label class="impulso-switch"><input id="impulso-setting-sound" type="checkbox" <?php echo !empty($settings_public['sound_enabled']) ? 'checked' : ''; ?>><span></span></label></div>
                        <div class="impulso-setting-row"><div class="impulso-setting-copy"><strong>Notificações do navegador</strong><span>Exibir notificações quando o Rise estiver em segundo plano.</span></div><label class="impulso-switch"><input id="impulso-setting-browser-notifications" type="checkbox" <?php echo !empty($settings_public['browser_notifications_enabled']) ? 'checked' : ''; ?>><span></span></label></div>
                        <div class="impulso-setting-row"><div class="impulso-setting-copy"><strong>Marcar como lida ao abrir</strong><span>Zerar o contador quando a conversa for selecionada.</span></div><label class="impulso-switch"><input id="impulso-setting-auto-read" type="checkbox" <?php echo array_key_exists('auto_mark_read', $settings_public) && empty($settings_public['auto_mark_read']) ? '' : 'checked'; ?>><span></span></label></div>
                    </div>
                </div>
                <div class="impulso-card">
                    <div class="impulso-card-header"><div><h3>Padrões de atendimento</h3><p>Valores usados em novas conversas</p></div></div>
                    <div class="impulso-card-body"><div class="impulso-field-grid"><div class="impulso-field"><label>Status inicial</label><select class="form-control" id="impulso-setting-default-status"><option value="open">Aberta</option><option value="pending">Pendente</option></select></div><div class="impulso-field"><label>Prioridade inicial</label><select class="form-control" id="impulso-setting-default-priority"><option value="normal">Normal</option><option value="low">Baixa</option><option value="high">Alta</option></select></div><div class="impulso-field"><label>SLA de primeira resposta</label><input class="form-control" id="impulso-setting-sla-minutes" type="number" min="1" value="<?php echo (int) ($settings_public['sla_minutes'] ?? 30); ?>"><small>Minutos</small></div><div class="impulso-field"><label>Resolver inativas após</label><input class="form-control" id="impulso-setting-auto-resolve-hours" type="number" min="0" value="<?php echo (int) ($settings_public['auto_resolve_hours'] ?? 0); ?>"><small>Horas; 0 desativa</small></div></div></div>
                </div>
            </section>

            <section class="impulso-settings-panel" data-settings-panel="evolution">
                <div class="impulso-card">
                    <div class="impulso-card-header"><div><h3>Evolution API</h3><p>Servidor usado para consultas e envio pelo WhatsApp</p></div><span class="impulso-badge <?php echo !empty($settings_public['evolution_base_url']) ? 'success' : 'warning'; ?>"><span class="impulso-dot"></span><?php echo !empty($settings_public['evolution_base_url']) ? 'Configurada' : 'Pendente'; ?></span></div>
                    <div class="impulso-card-body"><div class="impulso-field-grid">
                        <div class="impulso-field full"><label>URL base</label><input class="form-control" id="impulso-setting-base-url" type="url" value="<?php echo esc($settings_public['evolution_base_url'] ?? ''); ?>" placeholder="https://evolution.exemplo.com"></div>
                        <div class="impulso-field full"><label>API key global</label><div class="input-group"><input class="form-control" id="impulso-setting-global-key" type="password" autocomplete="new-password" placeholder="Deixe vazio para manter a chave atual"><button class="btn btn-default" type="button" data-impulso-action="toggle-password"><i data-feather="eye"></i></button></div><small>Atual: <span id="impulso-global-key-mask"><?php echo esc($settings_public['global_api_key_masked'] ?? 'Não configurada'); ?></span></small></div>
                        <div class="impulso-field"><label>Timeout (segundos)</label><input class="form-control" id="impulso-setting-timeout" type="number" min="3" max="120" value="<?php echo (int) ($settings_public['request_timeout_seconds'] ?? 30); ?>"></div>
                        <div class="impulso-field"><label>Máximo de tentativas</label><input class="form-control" id="impulso-setting-evolution-retries" type="number" min="0" max="5" value="<?php echo (int) ($settings_public['evolution_retries'] ?? 2); ?>"></div>
                        <div class="impulso-field full"><label>Endpoint de estado</label><input class="form-control" id="impulso-setting-status-path" value="<?php echo esc($settings_public['connection_status_path'] ?? '/instance/connectionState/{instance}'); ?>"></div>
                        <div class="impulso-field full"><label>Endpoint de conversas</label><input class="form-control" id="impulso-setting-chats-path" value="<?php echo esc($settings_public['find_chats_path'] ?? '/chat/findChats/{instance}'); ?>"></div>
                        <div class="impulso-field full"><label>Endpoint de histórico</label><input class="form-control" id="impulso-setting-messages-path" value="<?php echo esc($settings_public['find_messages_path'] ?? '/chat/findMessages/{instance}'); ?>"></div>
                        <div class="impulso-field full"><label>Endpoint de envio de texto</label><input class="form-control" id="impulso-setting-send-path" value="<?php echo esc($settings_public['send_text_path'] ?? '/message/sendText/{instance}'); ?>"></div>
                        <div class="impulso-field full"><label>Endpoint de envio de mídia</label><input class="form-control" id="impulso-setting-send-media-path" value="<?php echo esc($settings_public['send_media_path'] ?? '/message/sendMedia/{instance}'); ?>"></div>
                        <div class="impulso-field full"><label>Endpoint de áudio WhatsApp</label><input class="form-control" id="impulso-setting-send-audio-path" value="<?php echo esc($settings_public['send_audio_path'] ?? '/message/sendWhatsAppAudio/{instance}'); ?>"></div>
                        <div class="impulso-field full"><label>Endpoint de recuperação de mídia</label><input class="form-control" id="impulso-setting-media-base64-path" value="<?php echo esc($settings_public['get_media_base64_path'] ?? '/chat/getBase64FromMediaMessage/{instance}'); ?>"></div>
                    </div><div class="impulso-card-actions"><button class="btn btn-default" type="button" data-impulso-action="test-evolution"><i data-feather="activity"></i> Testar conexão</button></div></div>
                </div>
            </section>

            <section class="impulso-settings-panel" data-settings-panel="n8n">
                <div class="impulso-card impulso-mb-14">
                    <div class="impulso-card-header"><div><h3>Conexão com o n8n</h3><p>API central para campanhas, IA e automações</p></div><button class="btn btn-default btn-sm" type="button" data-impulso-action="test-n8n"><i data-feather="activity"></i> Testar</button></div>
                    <div class="impulso-card-body"><div class="impulso-field-grid">
                        <div class="impulso-field full"><label>URL base do n8n</label><input class="form-control" id="impulso-setting-n8n-base-url" type="url" value="<?php echo esc($settings_public['n8n_base_url'] ?? ''); ?>" placeholder="https://n8n.exemplo.com"></div>
                        <div class="impulso-field full"><label>Token de integração</label><div class="input-group"><input class="form-control" id="impulso-setting-n8n-token" type="password" autocomplete="new-password" placeholder="Deixe vazio para manter"><button class="btn btn-default" type="button" data-impulso-action="toggle-password"><i data-feather="eye"></i></button></div><small>Atual: <?php echo esc($settings_public['n8n_token_masked'] ?? 'Não configurado'); ?></small></div>
                        <div class="impulso-field"><label>Timeout</label><input class="form-control" id="impulso-setting-n8n-timeout" type="number" min="3" max="120" value="<?php echo (int) ($settings_public['n8n_timeout_seconds'] ?? 30); ?>"></div>
                        <div class="impulso-field"><label>Assinatura HMAC</label><select class="form-control" id="impulso-setting-n8n-auth-mode"><option value="bearer">Bearer token</option><option value="hmac">HMAC-SHA256</option><option value="header">Header personalizado</option></select></div>
                        <div class="impulso-field"><label>Nome do header personalizado</label><input class="form-control" id="impulso-setting-n8n-header-name" value="<?php echo esc($settings_public['n8n_header_name'] ?? 'X-API-Key'); ?>" placeholder="X-API-Key"></div>
                        <div class="impulso-field full"><div class="impulso-setting-row"><div class="impulso-setting-copy"><strong>Permitir rede privada</strong><span>Ative somente quando o n8n estiver em uma rede interna confiável.</span></div><label class="impulso-switch"><input id="impulso-setting-n8n-private-networks" type="checkbox" <?php echo !empty($settings_public['n8n_allow_private_networks']) ? 'checked' : ''; ?>><span></span></label></div></div>
                    </div></div>
                </div>
                <div class="impulso-card">
                    <div class="impulso-card-header"><div><h3>Endpoints</h3><p>Use caminhos relativos à URL base, iniciados por /</p></div></div>
                    <div class="impulso-card-body"><div class="impulso-field-grid"><div class="impulso-field full"><label>Saúde</label><input class="form-control" id="impulso-setting-n8n-health-path" value="<?php echo esc($settings_public['n8n_health_path'] ?? '/webhook/impulso/health'); ?>"></div><div class="impulso-field full"><label>Controle de IA</label><input class="form-control" id="impulso-setting-n8n-ai-path" value="<?php echo esc($settings_public['n8n_ai_path'] ?? '/webhook/impulso/ai'); ?>"></div><div class="impulso-field full"><label>Campanhas</label><input class="form-control" id="impulso-setting-n8n-campaigns-path" value="<?php echo esc($settings_public['n8n_campaigns_path'] ?? '/webhook/campanha'); ?>"></div><div class="impulso-field full"><label>Eventos e logs</label><input class="form-control" id="impulso-setting-n8n-events-path" value="<?php echo esc($settings_public['n8n_events_path'] ?? '/webhook/impulso/events'); ?>"></div></div></div>
                </div>
            </section>

            <section class="impulso-settings-panel" data-settings-panel="campaigns">
                <div class="impulso-card impulso-mb-14"><div class="impulso-card-header"><div><h3>Regras de disparo</h3><p>Limites aplicados antes de enviar ao n8n</p></div></div><div class="impulso-card-body"><div class="impulso-field-grid"><div class="impulso-field"><label>Horário inicial</label><input class="form-control" id="impulso-setting-campaign-start" type="time" value="<?php echo esc($settings_public['campaign_start_time'] ?? '08:00'); ?>"></div><div class="impulso-field"><label>Horário final</label><input class="form-control" id="impulso-setting-campaign-end" type="time" value="<?php echo esc($settings_public['campaign_end_time'] ?? '20:00'); ?>"></div><div class="impulso-field"><label>Intervalo mínimo</label><input class="form-control" id="impulso-setting-campaign-min-interval" type="number" min="1" value="<?php echo (int) ($settings_public['campaign_min_interval_seconds'] ?? 10); ?>"><small>Segundos</small></div><div class="impulso-field"><label>Lote máximo</label><input class="form-control" id="impulso-setting-campaign-batch-size" type="number" min="1" max="1000" value="<?php echo (int) ($settings_public['campaign_batch_size'] ?? 100); ?>"></div></div><div class="impulso-setting-row impulso-mt-14"><div class="impulso-setting-copy"><strong>Remover opt-outs</strong><span>Excluir automaticamente contatos bloqueados.</span></div><label class="impulso-switch"><input id="impulso-setting-campaign-optout" type="checkbox" checked><span></span></label></div><div class="impulso-setting-row"><div class="impulso-setting-copy"><strong>Pausar em falha sistêmica</strong><span>Interromper após uma sequência de erros de API.</span></div><label class="impulso-switch"><input id="impulso-setting-campaign-pause-errors" type="checkbox" checked><span></span></label></div></div></div>
                <div class="impulso-card"><div class="impulso-card-header"><div><h3>Templates rápidos</h3><p>Respostas disponíveis no composer e nas campanhas</p></div><button class="btn btn-default btn-sm" type="button" data-impulso-action="manage-quick-replies">Gerenciar</button></div><div class="impulso-card-body"><textarea class="form-control impulso-code-input" id="impulso-setting-quick-replies" rows="10" placeholder='[{"title":"Saudação","text":"Olá! Tudo bem?"}]'><?php echo esc($settings_public['quick_replies_json'] ?? ''); ?></textarea></div></div>
            </section>

            <section class="impulso-settings-panel" data-settings-panel="ai">
                <div class="impulso-card impulso-mb-14"><div class="impulso-card-header"><div><h3>Política de IA</h3><p>O processamento permanece no n8n; o plugin controla estados e exibe contexto</p></div></div><div class="impulso-card-body"><div class="impulso-field-grid"><div class="impulso-field"><label>Estado padrão</label><select class="form-control" id="impulso-setting-ai-default-state"><option value="running">IA ativa</option><option value="paused">IA pausada</option><option value="human">Humano</option></select></div><div class="impulso-field"><label>Tempo para devolver à IA</label><input class="form-control" id="impulso-setting-ai-return-minutes" type="number" min="0" value="<?php echo (int) ($settings_public['ai_return_minutes'] ?? 0); ?>"><small>0 mantém o estado manual</small></div><div class="impulso-field full"><label>Comando para pausar</label><input class="form-control" id="impulso-setting-ai-stop-command" value="<?php echo esc($settings_public['ai_stop_command'] ?? '@stop'); ?>"></div><div class="impulso-field full"><label>Comando para retomar</label><input class="form-control" id="impulso-setting-ai-start-command" value="<?php echo esc($settings_public['ai_start_command'] ?? '@start'); ?>"></div></div><div class="impulso-setting-row impulso-mt-14"><div class="impulso-setting-copy"><strong>Pausar IA quando humano enviar mensagem</strong><span>Evita concorrência entre resposta automática e atendente.</span></div><label class="impulso-switch"><input id="impulso-setting-ai-human-priority" type="checkbox" checked><span></span></label></div><div class="impulso-setting-row"><div class="impulso-setting-copy"><strong>Mostrar resumo operacional</strong><span>Exibir estágio, intenção e dados coletados no painel lateral.</span></div><label class="impulso-switch"><input id="impulso-setting-ai-show-context" type="checkbox" checked><span></span></label></div></div></div>
            </section>

            <section class="impulso-settings-panel" data-settings-panel="webhooks">
                <div class="impulso-card impulso-mb-14"><div class="impulso-card-header"><div><h3>Webhook do plugin</h3><p>Destino dos eventos da Evolution ou do n8n</p></div><button class="btn btn-default btn-sm" type="button" data-impulso-action="copy-webhook"><i data-feather="copy"></i> Copiar</button></div><div class="impulso-card-body"><div class="impulso-code" id="impulso-webhook-endpoint">POST <?php echo esc($webhook_endpoint ?? get_uri('chatwoot_plugin/webhooks/evolution')); ?>
X-Chatwoot-Webhook-Secret: <?php echo esc($settings_public['webhook_secret_masked'] ?? 'não configurado'); ?>
Content-Type: application/json</div><div class="impulso-field impulso-mt-14"><label>Novo segredo</label><div class="input-group"><input class="form-control" id="impulso-setting-webhook-secret" type="password" autocomplete="new-password" placeholder="Deixe vazio para manter"><button class="btn btn-default" type="button" data-impulso-action="toggle-password"><i data-feather="eye"></i></button></div><small>Atual: <span id="impulso-webhook-secret-mask"><?php echo esc($settings_public['webhook_secret_masked'] ?? 'Não configurado'); ?></span></small></div><div class="impulso-setting-row impulso-mt-14"><div class="impulso-setting-copy"><strong>Registrar payload sanitizado</strong><span>Necessário para deduplicação e diagnóstico.</span></div><label class="impulso-switch"><input id="impulso-setting-log-webhooks" type="checkbox" checked><span></span></label></div></div></div>
                <div class="impulso-card"><div class="impulso-card-header"><div><h3>Eventos habilitados</h3><p>Selecione no Evolution Manager</p></div></div><div class="impulso-card-body"><div class="impulso-tag-list"><span class="impulso-badge primary">MESSAGES_UPSERT</span><span class="impulso-badge primary">MESSAGES_UPDATE</span><span class="impulso-badge primary">CONNECTION_UPDATE</span><span class="impulso-badge primary">CHATS_UPSERT</span><span class="impulso-badge primary">CONTACTS_UPSERT</span></div></div></div>
            </section>

            <section class="impulso-settings-panel" data-settings-panel="security">
                <div class="impulso-card impulso-mb-14"><div class="impulso-card-header"><div><h3>Segurança e auditoria</h3><p>Proteção de credenciais e rastreabilidade</p></div></div><div class="impulso-card-body"><div class="impulso-setting-row"><div class="impulso-setting-copy"><strong>Criptografar credenciais</strong><span>Obrigatório para chaves Evolution e n8n.</span></div><label class="impulso-switch"><input type="checkbox" checked disabled><span></span></label></div><div class="impulso-setting-row"><div class="impulso-setting-copy"><strong>Auditar ações dos atendentes</strong><span>Registrar envio, resolução, atribuição, campanhas e alterações.</span></div><label class="impulso-switch"><input id="impulso-setting-audit-enabled" type="checkbox" checked><span></span></label></div><div class="impulso-setting-row"><div class="impulso-setting-copy"><strong>Bloquear URL de mídia insegura</strong><span>Aceitar somente HTTPS ou URLs assinadas da infraestrutura.</span></div><label class="impulso-switch"><input id="impulso-setting-secure-media" type="checkbox" checked><span></span></label></div></div></div>
                <div class="impulso-card"><div class="impulso-card-header"><div><h3>Retenção</h3><p>Prazo para limpeza automática</p></div></div><div class="impulso-card-body"><div class="impulso-field-grid"><div class="impulso-field"><label>Webhooks técnicos</label><input class="form-control" id="impulso-setting-webhook-retention" type="number" min="1" value="<?php echo (int) ($settings_public['webhook_retention_days'] ?? 30); ?>"><small>Dias</small></div><div class="impulso-field"><label>Logs de auditoria</label><input class="form-control" id="impulso-setting-audit-retention" type="number" min="1" value="<?php echo (int) ($settings_public['audit_retention_days'] ?? 180); ?>"><small>Dias</small></div><div class="impulso-field"><label>Cache de mídia</label><input class="form-control" id="impulso-setting-media-retention" type="number" min="0" value="<?php echo (int) ($settings_public['media_retention_days'] ?? 7); ?>"><small>Dias</small></div><div class="impulso-field"><label>Conversas resolvidas</label><input class="form-control" id="impulso-setting-conversation-retention" type="number" min="0" value="<?php echo (int) ($settings_public['conversation_retention_days'] ?? 0); ?>"><small>0 não remove</small></div></div></div></div>
            </section>
        </div>
    </div>
</div>
