<?php
declare(strict_types=1);
namespace Chatwoot_plugin\Services;
use Chatwoot_plugin\Libraries\N8n_client;
use Chatwoot_plugin\Models\Chat_automations_model;
use Chatwoot_plugin\Models\Chat_instances_model;
use Chatwoot_plugin\Models\Chat_settings_model;
use InvalidArgumentException;
use RuntimeException;
class Automation_service
{
    public function __construct(private ?Chat_automations_model $models=null,private ?Chat_instances_model $instances=null,private ?Chat_settings_model $settings=null,private ?N8n_client $n8n=null,private ?Audit_service $audit=null){$this->models??=new Chat_automations_model();$this->instances??=new Chat_instances_model();$this->settings??=new Chat_settings_model();$this->n8n??=new N8n_client($this->settings);$this->audit??=new Audit_service();}
    public function list(array $filters,int $page,int $limit):array{$r=$this->models->paginate_records($filters,$page,$limit);$r['data']=array_map([$this,'map'],$r['data']);return $r;}
    public function get(int $id):?array{$r=$this->models->get_by_id($id);return $r?$this->map($r):null;}
    public function save(array $input,int $actor,?int $id=null):array{
        $name=trim((string)($input['name']??''));$trigger=trim((string)($input['trigger_event']??$input['trigger']??''));$path=$this->normalizePath(trim((string)($input['webhook_path']??$input['webhook_url']??$this->settings->get_value('n8n_events_path','/webhook/impulso/events'))));
        if($name===''||mb_strlen($name)>191||$trigger===''||mb_strlen($trigger)>100)throw new InvalidArgumentException('Nome e gatilho da automacao sao obrigatorios.');
        if(!str_starts_with($path,'/')||str_contains($path,'://')||preg_match('/[\r\n?#]/',$path))throw new InvalidArgumentException('Webhook da automacao invalido.');
        $instanceId=!empty($input['instance_id'])?(int)$input['instance_id']:null;if($instanceId&&!$this->instances->get_by_id($instanceId))throw new InvalidArgumentException('Instancia invalida.');
        $conditions=$input['conditions']??[];if(is_string($conditions)){$conditions=json_decode($conditions,true);if(!is_array($conditions))throw new InvalidArgumentException('Condicoes JSON invalidas.');}if(!is_array($conditions))$conditions=[];
        $before=$id?$this->models->get_by_id($id):null;if($id&&!$before)throw new RuntimeException('Automacao nao encontrada.',404);
        $payload=['name'=>$name,'trigger_event'=>$trigger,'conditions_json'=>json_encode($conditions,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'webhook_path'=>$path,'instance_id'=>$instanceId,'delay_seconds'=>min(86400,max(0,(int)($input['delay_seconds']??0))),'active'=>filter_var($input['active']??true,FILTER_VALIDATE_BOOLEAN)?1:0,'created_by'=>$actor];
        if($id)$this->models->update_record($id,$payload);else$id=$this->models->create_record($payload);$saved=$this->get($id)?:[];
        $response=$this->n8n->request('POST',$this->eventsPath(),['action'=>'automation.upsert','automation'=>$saved,'contract_version'=>'1.1.0'],['idempotency_key'=>hash('sha256',json_encode($saved)),'idempotent'=>true]);if(!$response['success'])throw new RuntimeException((string)$response['error'],502);
        $this->audit->record($actor,$before?'automation.updated':'automation.created','automation',$id,$instanceId,$before?:[],$saved,$response['correlation_id']);return $saved;
    }
    public function toggle(int $id,int $actor):array{$row=$this->models->get_by_id($id);if(!$row)throw new RuntimeException('Automacao nao encontrada.',404);$active=empty($row['active'])?1:0;$response=$this->n8n->request('POST',$this->eventsPath(),['action'=>'automation.toggle','automation_id'=>$id,'active'=>(bool)$active],['idempotent'=>true]);if(!$response['success'])throw new RuntimeException((string)$response['error'],502);$this->models->update_record($id,['active'=>$active]);$this->audit->record($actor,'automation.toggled','automation',$id,isset($row['instance_id'])?(int)$row['instance_id']:null,['active'=>!empty($row['active'])],['active'=>(bool)$active],$response['correlation_id']);return $this->get($id)?:[];}
    public function test(int $id,int $actor):array{$row=$this->get($id);if(!$row)throw new RuntimeException('Automacao nao encontrada.',404);$response=$this->n8n->request('POST',(string)$row['webhook_path'],['test'=>true,'dry_run'=>true,'automation_id'=>$id,'event'=>['name'=>$row['trigger_event'],'source'=>'rise_plugin_test'],'confirmation'=>false]);$this->models->update_record($id,['last_run_at'=>gmdate('Y-m-d H:i:s'),'last_status'=>$response['success']?'success':'failed','last_error'=>$response['error']]);if(!$response['success'])throw new RuntimeException((string)$response['error'],502);$this->audit->record($actor,'automation.tested','automation',$id,$row['instance_id'],[],['dry_run'=>true],$response['correlation_id']);return ['success'=>true,'dry_run'=>true,'correlation_id'=>$response['correlation_id'],'response'=>$response['data']];}
    public function delete(int $id,int $actor):void{$row=$this->models->get_by_id($id);if(!$row)throw new RuntimeException('Automacao nao encontrada.',404);$response=$this->n8n->request('POST',$this->eventsPath(),['action'=>'automation.delete','automation_id'=>$id],['idempotent'=>true]);if(!$response['success'])throw new RuntimeException((string)$response['error'],502);$this->models->soft_delete($id);$this->audit->record($actor,'automation.deleted','automation',$id,isset($row['instance_id'])?(int)$row['instance_id']:null,$row,[],$response['correlation_id']);}
    private function map(array $r):array{$path=(string)$r['webhook_path'];$base=rtrim((string)$this->settings->get_value('n8n_base_url',''),'/');return['id'=>(int)$r['id'],'name'=>(string)$r['name'],'trigger_event'=>(string)$r['trigger_event'],'trigger'=>(string)$r['trigger_event'],'conditions'=>$this->json((string)($r['conditions_json']??'')),'webhook_path'=>$path,'webhook_url'=>$base!==''?$base.'/'.ltrim($path,'/'):$path,'instance_id'=>isset($r['instance_id'])?(int)$r['instance_id']:null,'delay_seconds'=>(int)$r['delay_seconds'],'active'=>!empty($r['active']),'last_run_at'=>$r['last_run_at']??null,'last_status'=>$r['last_status']??null,'last_error'=>$r['last_error']??null,'created_at'=>$r['created_at']??null,'updated_at'=>$r['updated_at']??null];}
    private function json(string $v):array{$d=json_decode($v,true);return is_array($d)?$d:[];}private function eventsPath():string{return'/'.ltrim(trim((string)$this->settings->get_value('n8n_events_path','/webhook/impulso/events')),'/');}private function normalizePath(string $value):string{if(str_contains($value,'://')){$p=parse_url($value);$b=parse_url((string)$this->settings->get_value('n8n_base_url',''));if(!is_array($p)||!is_array($b)||strtolower((string)($p['host']??''))!==strtolower((string)($b['host']??'')))throw new InvalidArgumentException('O webhook deve pertencer a origem n8n configurada.');$value=(string)($p['path']??'');}return$value;}
}
